# Generated by Django 3.0.8 on 2020-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Remote Fulltime ', 'Remote Fulltime '), ('Remote part-time ', 'Remote part-time '), ('Fulltime on site ', 'Fulltime On site '), ('Part time on site', 'Part-time On site ')], max_length=20)),
                ('category', models.ManyToManyField(related_name='jobs', to='core.Category')),
            ],
        ),
    ]
