# Generated by Django 3.0.8 on 2020-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='recruiter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
