# Generated by Django 3.0.8 on 2020-07-05 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_opening_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 5, 5, 32, 27, 465659)),
            preserve_default=False,
        ),
    ]
