# Generated by Django 3.0.8 on 2020-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_opening_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='patners',
            name='logo',
            field=models.FileField(default=1, upload_to='patners/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
