# Generated by Django 3.0.8 on 2020-07-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patners_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patners',
            new_name='Patner',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
