# Generated by Django 3.0.8 on 2020-07-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_talent_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='title',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='image',
        ),
    ]
