# Generated by Django 3.0.8 on 2020-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200705_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='salary',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
